name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        wagtail-version: ['4.1', '4.2']
        DATABASE_URL: ['sqlite:///db.sqlite3', 'postgres://postgres:postgres@localhost/postgres']

    env:
      DATABASE_URL: ${{matrix.DATABASE_URL}}

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          cache-dependency-path: |
            tests/requirements.txt

      - name: Install Dependencies
        run: |
          cd tests
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Install Wagtail package
        if: ${{ matrix.wagtail-version != 'main' }}
        run: |
          python -m pip install wagtail==${{ matrix.wagtail-version }}

      - name: Install Wagtail main
        if: ${{ matrix.wagtail-version == 'main' }}
        run: |
          git clone https://github.com/wagtail/wagtail.git
          python -m pip install ./wagtail

      - name: Run Tests
        run: |
          cd tests
          python manage.py migrate
          python manage.py test
